### ISSUE TITLE
fix in prepareDataset

### ISSUE THREAD

**Issue by vvvin333** [kapulkin/ODSPetUnet#1]
I cannot push my first fixes in prepareDataset.py

**Comment by vvvin333** [comment]
![Снимок экрана от 2021-01-20 22-02-59](https://user-images.githubusercontent.com/60153443/105241392-482b5500-5b76-11eb-9dc2-cf012f6c92e2.png)

**Comment by kapulkin** [comment]
I mixed up this repo with actual repo for current Hackathon.
